## Plot the Data!!

In [133]:
import pandas as pd

dow_jones = pd.read_csv('^DJI.csv')
dow_jones = dow_jones.drop(["High","Low","Adj Close","Volume"],axis = 1)
dow_jones



Date          Open         Close
0     1985-01-29   1277.719971   1292.619995
1     1985-01-30   1297.369995   1287.880005
2     1985-01-31   1283.239990   1286.770020
3     1985-02-01   1276.939941   1277.719971
4     1985-02-04   1272.079956   1290.079956
...          ...           ...           ...
8867  2020-04-03  21285.929688  21052.529297
8868  2020-04-06  21693.630859  22679.990234
8869  2020-04-07  23537.439453  22653.859375
8870  2020-04-08  22893.470703  23433.570313
8871  2020-04-09  23690.660156  23719.369141

[8872 rows x 3 columns]

In [164]:
bad_rows = []
for row_ind,row in dow_jones.iterrows():
    year = row[0][2:4]
    if(float(year) < 18) or (float(year) > 20):
        bad_rows.append(row_ind)
dow_predict_df = dow_jones.drop(bad_rows,axis = 0)
dow_predict_df = np.array(dow_predict_df)
dow_time_predict = dow_predict_df[:,0]
dow_open_predict = dow_predict_df[:,1].astype(np.float)
dow_open_predict = dow_open_predict.reshape(-1,1)

In [3]:
snp_500 = pd.read_csv('^GSPC.csv')
snp_500 = snp_500.drop(["High","Low","Adj Close","Volume"],axis = 1)
snp_500



Date         Open        Close
0      1927-12-30    17.660000    17.660000
1      1928-01-03    17.760000    17.760000
2      1928-01-04    17.719999    17.719999
3      1928-01-05    17.549999    17.549999
4      1928-01-06    17.660000    17.660000
...           ...          ...          ...
23173  2020-04-03  2514.919922  2488.649902
23174  2020-04-06  2578.280029  2663.679932
23175  2020-04-07  2738.649902  2659.409912
23176  2020-04-08  2685.000000  2749.979980
23177  2020-04-09  2776.989990  2789.820068

[23178 rows x 3 columns]

In [165]:
bad_rows = []
for row_ind,row in snp_500.iterrows():
    year = row[0][2:4]
    if(float(year) < 18) or (float(year) > 20):
        bad_rows.append(row_ind)
snp_predict_df = snp_500.drop(bad_rows,axis = 0)
snp_predict_df = np.array(snp_predict_df)
snp_time_predict = snp_predict_df[:,0]
snp_open_predict = snp_predict_df[:,1].astype(np.float)
snp_open_predict = snp_open_predict.reshape(-1,1)

In [112]:
quarter_gdp = pd.read_csv('quarter_csv.csv')
quarter_gdp = quarter_gdp.drop(["level-chained","change-current","change-chained"],axis = 1)
quarter_gdp

date  level-current
0    1947-04-01          246.3
1    1947-07-01          250.1
2    1947-10-01          260.3
3    1948-01-01          266.2
4    1948-04-01          272.9
..          ...            ...
276  2016-04-01        18538.0
277  2016-07-01        18729.1
278  2016-10-01        18905.5
279  2017-01-01        19057.7
280  2017-04-01        19250.0

[281 rows x 2 columns]

In [5]:
year_gdp = pd.read_csv('year_csv.csv')
year_gdp = year_gdp.drop(["level-chained","change-current","change-chained"],axis = 1)
year_gdp

date  level-current
0   1930           92.2
1   1931           77.4
2   1932           59.5
3   1933           57.2
4   1934           66.8
..   ...            ...
81  2011        15517.9
82  2012        16155.3
83  2013        16691.5
84  2014        17427.6
85  2015        18120.7

[86 rows x 2 columns]

In [115]:
import numpy as np
yield_curve = pd.read_csv('yeild_curve_data - Sheet1 (1).csv')

yield_curve = yield_curve.drop(["2 Mo","3 Mo","6 Mo","1 Yr","2 Yr","3 Yr","5 Yr","7 Yr","10 Yr","30 Yr"],axis = 1)
yield_curve = yield_curve.dropna()


Date  1 Mo  20 Yr
396   07/31/01  3.67   5.61
397   08/01/01  3.65   5.63
398   08/02/01  3.65   5.68
399   08/03/01  3.63   5.70
400   08/06/01  3.62   5.70
...        ...   ...    ...
5068  04/06/20  0.09   1.08
5069  04/07/20  0.10   1.13
5070  04/08/20  0.14   1.18
5071  04/09/20  0.20   1.15
5072  04/13/20  0.17   1.19

[4676 rows x 3 columns]

In [147]:
bad_rows = []
for row_ind,row in yield_curve.iterrows():
    year = row[0][6:]
    year = "20" + year
    if(float(year) < 2018) or (float(year) > 2020):
        bad_rows.append(row_ind)
yield_predict_df = yield_curve.drop(bad_rows,axis = 0)
yield_predict_df = np.array(yield_predict_df)
yield_time_predict =yield_predict_df[:,0]
yield_onemonth_predict = yield_predict_df[:,1]
yield_twentyyear_predict = yield_predict_df[:,2]

In [7]:

dow_list = []

for row_ind,row in dow_jones.iterrows():
    string_month = row[0][5:7]
    string_year = row[0][2:4]
    for row_ind2,row2 in quarter_gdp.iterrows():
        string2_month = row2[0][5:7]
        string2_year = row2[0][2:4]
        if(string2_month == string_month) and (string_year == string2_year):
            row_tup = (row[0],row[1],row[2],row2[1])
            dow_list.append(row_tup)
dow_arr = np.array(dow_list)



(2729, 4)

In [197]:
from sklearn.model_selection import train_test_split
time = dow_arr[:,0]
open_prices = dow_arr[:,1]
dow_gdp = dow_arr[:,3]
open_prices = open_prices.astype(np.float)
open_prices = open_prices.reshape(-1,1)



In [198]:
gdp_binary = []

for i in range(len(dow_gdp)):

    if(i < len(dow_gdp)-1):
   
        if(dow_gdp[i+1] < dow_gdp[i]):
            gdp_binary.append(0)
        elif(dow_gdp[i+1] == dow_gdp[i]):
            gdp_binary.append(1)
        elif(dow_gdp[i+1] > dow_gdp[i]):
            gdp_binary.append(2)
    else:
        gdp_binary.append(1)
gdp_classifier = gdp_binary      

In [199]:
from sklearn.neighbors import KNeighborsClassifier

dow_train,dow_test,gdp_train,gdp_test = train_test_split(open_prices,gdp_classifier,test_size = 0.3)
model = KNeighborsClassifier(n_neighbors=2)
model.fit(dow_train,gdp_train)
prediction = model.predict(dow_test)
prediction


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [200]:
for i in prediction:
    if i == 0:
        print("found0")
    if i == 2:
        print("found2")

found0
found0
found0


In [201]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(gdp_test,prediction)
print(accuracy)

0.9511599511599511


In [202]:
dow_open_predict.shape


(572, 1)

In [203]:
two_dow = model.predict(dow_open_predict)
for i in two_dow:
    if i == 0:
        print("found0")
    if i == 2:
        print("found2")

In [72]:
snp_list = []

for row_ind,row in snp_500.iterrows():
    string_month = row[0][5:7]
    string_year = row[0][2:4]
    for row_ind2,row2 in quarter_gdp.iterrows():
        string2_month = row2[0][5:7]
        string2_year = row2[0][2:4]
        if(string2_month == string_month) and (string_year == string2_year):
            row_tup = (row[0],row[1],row[2],row2[1])
            snp_list.append(row_tup)
snp_arr = np.array(snp_list)
snp_arr.shape

KeyboardInterrupt: 

Exception ignored in: 'pandas._libs.lib.c_is_list_like'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
KeyboardInterrupt


(5943, 4)

In [83]:
time = snp_arr[:,0]
open_prices = snp_arr[:,1]
snp_gdp = snp_arr[:,3]
open_prices = open_prices.astype(np.float)
open_prices = open_prices.reshape(-1,1)

In [87]:
gdp_binary = []

for i in range(len(snp_gdp)):

    if(i < len(snp_gdp)-1):
   
        if(snp_gdp[i+1] < snp_gdp[i]):
            gdp_binary.append(0)
        elif(snp_gdp[i+1] == snp_gdp[i]):
            gdp_binary.append(1)
        elif(snp_gdp[i+1] > snp_gdp[i]):
            gdp_binary.append(2)
    else:
        gdp_binary.append(1)
gdp_classifier = gdp_binary  

In [88]:
from sklearn.neighbors import KNeighborsClassifier

snp_train,snp_test,gdp_train,gdp_test = train_test_split(open_prices,gdp_classifier,test_size = 0.3)
model = KNeighborsClassifier(n_neighbors=2)
model.fit(snp_train,gdp_train)
prediction = model.predict(snp_test)
prediction

array([1, 1, 1, ..., 1, 1, 1])

In [89]:
for i in prediction:
    if i == 0:
        print("found0")
    if i == 2:
        print("found2")

found0
found0
found0
found0
found0
found0
found0
found0
found2
found0
found0
found0
found0
found0
found2
found0
found0
found0
found0
found0


In [90]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(gdp_test,prediction)
print(accuracy)

0.944475602916433


In [116]:
yield_list = []

for row_ind, row in yield_curve.iterrows():
    string_month = row[0][0:2]
    string_year = row[0][6:8]
    for row_ind2,row2 in quarter_gdp.iterrows():
        string2_month = row2[0][5:7]
        string2_year = row2[0][2:4]
        if(string2_month == string_month) and (string_year == string2_year):
            row_list = []
            for item in row:
                row_list.append(item)
            row_list.append(row2[1])
            yield_list.append(row_list)
yield_arr = np.array(yield_list)
yield_arr.shape

(1317, 4)

In [117]:
time = yield_arr[:,0]
one_mo = yield_arr[:,1].astype(np.float)
twenty_year = yield_arr[:,2].astype(np.float)
yield_gdp = yield_arr[:,3]
all_yield = np.stack((one_mo,twenty_year),axis = -1)

In [118]:
all_yield

array([[3.67, 5.61],
       [2.26, 5.39],
       [2.27, 5.36],
       ...,
       [0.74, 2.69],
       [0.7 , 2.68],
       [0.68, 2.67]])

In [119]:
gdp_binary = []

for i in range(len(yield_gdp)):

    if(i < len(yield_gdp)-1):
   
        if(yield_gdp[i+1] < yield_gdp[i]):
            gdp_binary.append(0)
        elif(yield_gdp[i+1] == yield_gdp[i]):
            gdp_binary.append(1)
        elif(yield_gdp[i+1] > yield_gdp[i]):
            gdp_binary.append(2)
    else:
        gdp_binary.append(1)
gdp_classifier = gdp_binary  

In [122]:
from sklearn.neighbors import KNeighborsClassifier

yield_train,yield_test,gdp_train,gdp_test = train_test_split(all_yield,gdp_classifier,test_size = 0.3)
model = KNeighborsClassifier(n_neighbors=2)
model.fit(yield_train,gdp_train)
prediction = model.predict(yield_test)
prediction

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [123]:
for i in prediction:
    if i == 0:
        print("found0")
    if i == 2:
        print("found2")

found0
found2


In [124]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(gdp_test,prediction)
print(accuracy)

0.9545454545454546


In [126]:
prediction = model.predict(all_yield)
for i in prediction:
    if i == 0:
        print("found0")
    if i == 2:
        print("found2")
accuracy = accuracy_score(gdp_classifier,prediction)
print(accuracy)

found0
found0
found0
found0
found0
found2
found2
found2
found2
0.9544419134396356
